--1. From SH.CUSTOMERS, display customer ID, first name, last name, gender, and marital status for all female customers.

SELECT cust_id, cust_first_name, cust_last_name,
 cust_gender, cust_marital_status 
FROM SH.CUSTOMERS
WHERE cust_gender = 'F';

--2.From SH.CUSTOMERS, find customers whose last name starts with S and whose year of birth is greater than 1970.

SELECT cust_id,
 cust_first_name, cust_last_name, cust_year_of_birth
FROM SH.CUSTOMERS 
WHERE cust_last_name LIKE 'S%'
 AND cust_year_of_birth > 1970;

--3.From SH.PRODUCTS, display product ID, product name, category, and list price for products whose list price is between 100 and 500.

 SELECT prod_id,
  prod_name, prod_category, prod_list_price
 FROM SH.PRODUCTS
 WHERE prod_list_price BETWEEN 100 AND 500;

--4.From SH.PRODUCTS, find products whose minimum price is less than 50 and whose status is available.

SELECT prod_id,
    prod_name, prod_min_price, prod_status
FROM SH.PRODUCTS 
WHERE prod_min_price < 50
 AND prod_status = 'available';

--5.From SH.SALES, display product ID, customer ID, quantity sold, and amount sold for transactions where the amount sold is greater than 1000.

 SELECT prod_id, cust_id, quantity_sold, amount_sold
 FROM SH.SALES
 WHERE amount_sold > 1000;

--6.From SH.SALES, find transactions where the quantity sold is greater than 2 and the channel ID is 3. 

SELECT prod_id, cust_id, quantity_sold, channel_id
 FROM SH.SALES
 WHERE quantity_sold > 2
  AND channel_id = 3;

--7.From SH.CHANNELS, display channel ID and channel description for channels whose description contains the word Direct.  

SELECT channel_id, channel_desc
FROM SH.CHANNELS
WHERE channel_desc LIKE '%Direct%';

--8.From SH.PROMOTIONS, display promotion ID, promotion name, cost, and category where promotion cost is greater than 1000.

SELECT promo_id, promo_name, promo_cost, promo_category
FROM SH.PROMOTIONS
WHERE promo_cost > 1000;

--9.From SH.PROMOTIONS, find promotions whose end date is greater than their begin date and whose promotion cost is greater than 500.

SELECT promo_id,
   promo_name, promo_begin_date, promo_end_date, promo_cost
FROM SH.PROMOTIONS
WHERE promo_end_date > promo_begin_date
 AND promo_cost > 500;

--10.From SH.COUNTRIES, display country ID, country name, and region ID for countries belonging to region ID 52790.

SELECT country_id, country_name, country_region
FROM SH.COUNTRIES
WHERE country_region_id = 52790;

--11.From SH.TIMES, display time ID, day name, calendar month name, and calendar year for dates belonging to the year 2000.

SELECT time_id, day_name, calendar_month_name, calendar_year 
FROM SH.TIMES
WHERE calendar_year = 2000;

--12.From SH.TIMES, find all dates where the calendar month name is December and the calendar year is 2001.

SELECT time_id, day_name, calendar_month_name, calendar_year
FROM SH.TIMES
WHERE calendar_month_name = 'December'
 AND calendar_year = 2001;

--13.From SH.COSTS, display product ID, time ID, unit cost, and unit price where unit price is greater than unit cost. 

SELECT prod_id, time_id, unit_cost, unit_price
FROM SH.COSTS
WHERE unit_price > unit_cost;

--14.From SH.COSTS, find records where unit cost is greater than 100 and unit price is less than 1000.

SELECT prod_id, time_id, unit_cost, unit_price
FROM SH.COSTS
WHERE unit_cost > 100
 AND unit_price < 1000;

--15.From SH.SUPPLEMENTARY_DEMOGRAPHICS, display customer ID, education, occupation, and household size for customers whose household size is greater than 3.

SELECT cust_id,
   education, occupation, household_size
FROM SH.SUPPLEMENTARY_DEMOGRAPHICS
WHERE household_size > '3'; 

--16.Using SH.CUSTOMERS, find the number of customers belonging to each marital status.

SELECT cust_marital_status, 
   COUNT(*) AS cust_count 
FROM SH.CUSTOMERS
  GROUP BY cust_marital_status;

--17.Using SH.CUSTOMERS, find the average customer year of birth for each gender.   

SELECT cust_gender, AVG(cust_year_of_birth) AS cust_avg_year_of_birth
FROM SH.CUSTOMERS
GROUP BY cust_gender;

--18.Using SH.PRODUCTS, find the average list price of products in each product category.

SELECT prod_category, AVG(prod_list_price) AS prod_avg_list_price
FROM SH.PRODUCTS
 GROUP BY prod_category;

--19.Using SH.PRODUCTS, find the highest minimum price in each product subcategory. 

SELECT prod_subcategory, MAX(prod_min_price) AS max_min_price
FROM SH.PRODUCTS
GROUP BY prod_subcategory;

--20.Using SH.SALES, calculate the total sales amount generated by each channel.

SELECT channel_id,
 SUM(amount_sold) AS total_sales
FROM SH.SALES
GROUP BY channel_id;

--21.Using SH.SALES, calculate the total quantity sold for each product.

SELECT prod_id,
 SUM(quantity_sold) AS total_quantity
FROM SH.SALES
GROUP BY prod_id;

--22.Using SH.SALES, find the average sales amount for each promotion.

SELECT promo_id,
 AVG(amount_sold) AS avg_sales_amount
FROM SH.SALES
GROUP BY promo_id;

--23.Using SH.PROMOTIONS, calculate the total promotion cost for each promotion category.

SELECT promo_category, SUM(promo_cost) AS total_promo_cost
FROM SH.PROMOTIONS
GROUP BY promo_category;

--24.Using SH.COUNTRIES, count the number of countries belonging to each region.

SELECT country_region, COUNT(*) AS country_count
FROM SH.COUNTRIES
GROUP BY country_region;

--25.Using SH.COSTS, calculate the average unit cost for each product.

SELECT prod_id,
   AVG(unit_cost) AS avg_unit_cost
FROM SH.COSTS
GROUP BY prod_id;

--26.Using SH.CUSTOMERS, count customers by gender and marital status.

SELECT cust_gender, cust_marital_status, COUNT(*) AS customer_count
FROM SH.CUSTOMERS
GROUP BY cust_gender, cust_marital_status;

--27.Using SH.PRODUCTS, count products by product category and product subcategory.

SELECT prod_category, prod_subcategory, COUNT(*) AS product_count
FROM SH.PRODUCTS
GROUP BY prod_category, prod_subcategory;

--28.Using SH.SALES, calculate total sales amount for each product and channel combination.

SELECT prod_id, channel_id, 
  SUM(amount_sold) AS total_sales
FROM SH.SALES
GROUP BY prod_id, channel_id;

--29.Using SH.SALES, calculate total quantity sold for each channel and promotion combination.

SELECT channel_id, promo_id,
  SUM(quantity_sold) AS total_quantity
FROM SH.SALES
GROUP BY channel_id, promo_id;

--30.Using SH.COSTS, find the average unit cost for each product and promotion combination.

SELECT prod_id, promo_id,
  AVG(unit_cost) AS avg_unit_cost
FROM SH.COSTS
GROUP BY prod_id, promo_id;

--31.From SH.SALES, consider only transactions where AMOUNT_SOLD > 500 and calculate total sales amount for each channel.

SELECT channel_id, 
  SUM(amount_sold) AS total_sales
FROM SH.SALES
WHERE amount_sold > 500
GROUP BY channel_id;

--32.From SH.PRODUCTS, consider only products whose list price is greater than 100 and find the average list price for each product category.

SELECT prod_category, AVG(prod_list_price) AS prod_avg_list_price
FROM SH.PRODUCTS
WHERE prod_list_price > 100
GROUP BY prod_category;

--33.From SH.CUSTOMERS, consider only customers born after 1970 and count them by marital status.

SELECT cust_marital_status, COUNT(*) AS customer_count
FROM SH.CUSTOMERS
WHERE cust_year_of_birth > 1970
GROUP BY cust_marital_status;

--34.From SH.PROMOTIONS, consider only promotions whose cost is greater than 500 and calculate the average promotion cost for each promotion category.

SELECT promo_category, AVG(promo_cost) AS avg_promo_cost
FROM SH.PROMOTIONS
WHERE promo_cost > 500
GROUP BY promo_category;

--35.From SH.COSTS, consider records where unit cost is greater than 50 and calculate the maximum unit price for each product.

SELECT prod_id,
   MAX(unit_price) AS max_unit_price
FROM SH.COSTS
WHERE unit_cost > 50
GROUP BY prod_id;

--36.Using SH.CUSTOMERS, display marital statuses having more than 100 customers.

SELECT cust_marital_status, COUNT(*) AS cust_count
FROM SH.CUSTOMERS
GROUP BY cust_marital_status
HAVING COUNT(*) > 100;

--37.Using SH.PRODUCTS, display product categories whose average list price is greater than 500.

SELECT prod_category, AVG(prod_list_price) AS avg_list_price
FROM SH.PRODUCTS
GROUP BY prod_category
HAVING AVG(prod_list_price) > 500;

--38.Using SH.SALES, display channels whose total sales amount is greater than 100000.

SELECT channel_id, SUM(amount_sold) AS total_sales
FROM SH.SALES
GROUP BY channel_id
HAVING SUM(amount_sold) > 100000;

--39.Using SH.PROMOTIONS, display promotion categories whose average promotion cost is greater than 1000.

SELECT promo_category, AVG(promo_cost) AS avg_promo_cost
FROM SH.PROMOTIONS
GROUP BY promo_category 
HAVING AVG(promo_cost) > 1000;

--40.Using SH.COSTS, display products whose average unit price is greater than 500.

SELECT prod_id,
  AVG(unit_price) AS avg_unit_price
FROM SH.COSTS GROUP BY prod_id
HAVING AVG(unit_price) > 500;